In [1]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

Get the shape of the matrix.

In [2]:
print(data.shape)

(5, 3)


Find the average age of students.

In [3]:
avg = data[0:,0]
print(avg.mean())

18.4


Extract Math marks of all students.

In [4]:
maths = data[:,1]
print(maths)

[85 92 76 65 90]


Find the highest Science mark.

In [5]:
science = data[:,2]
print(science.max())


95


In [6]:
print(np.max(data[:,2]))

95


Get details of the student who scored more than 90 in Math.

In [7]:
print(data[data[:,1] > 90])

[[19 92 88]]


Increase Math marks of all students by 5.

In [8]:
print(data[:,1]+5)

[90 97 81 70 95]


Find how many students are younger than 19.

In [9]:
age = data[0:,0:1]
count = 0
for i in age:
  if i < 19:
    count = count +1
print(count)

3


In [10]:
print(len(data[data[:,0] < 19]))

3


Calculate the average marks in each subject (column-wise mean).

In [11]:
print(np.mean(data[:,1:],axis=0))

[81.6 83.2]


Get data of students who scored at least 80 in both subjects.

In [12]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

Replace all Science marks < 75 with 0.

In [14]:
data[:,2] [data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])