In [2]:
print("Hello WOrld")

Hello WOrld


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a = [1,2,"hello",9.5]
np.array(a)


array(['1', '2', 'hello', '9.5'], dtype='<U32')

In [5]:
ar = [9.5,4,2,3]
np.array(ar)

array([9.5, 4. , 2. , 3. ])

In [6]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr = np.arange(1,15,3)
arr

array([ 1,  4,  7, 10, 13])

In [9]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [10]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr = np.ones((4,4))

In [12]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
arr = np.linspace(1,10,4)
arr

array([ 1.,  4.,  7., 10.])

In [14]:
arr = np.linspace(1,11,100)
arr

array([ 1.        ,  1.1010101 ,  1.2020202 ,  1.3030303 ,  1.4040404 ,
        1.50505051,  1.60606061,  1.70707071,  1.80808081,  1.90909091,
        2.01010101,  2.11111111,  2.21212121,  2.31313131,  2.41414141,
        2.51515152,  2.61616162,  2.71717172,  2.81818182,  2.91919192,
        3.02020202,  3.12121212,  3.22222222,  3.32323232,  3.42424242,
        3.52525253,  3.62626263,  3.72727273,  3.82828283,  3.92929293,
        4.03030303,  4.13131313,  4.23232323,  4.33333333,  4.43434343,
        4.53535354,  4.63636364,  4.73737374,  4.83838384,  4.93939394,
        5.04040404,  5.14141414,  5.24242424,  5.34343434,  5.44444444,
        5.54545455,  5.64646465,  5.74747475,  5.84848485,  5.94949495,
        6.05050505,  6.15151515,  6.25252525,  6.35353535,  6.45454545,
        6.55555556,  6.65656566,  6.75757576,  6.85858586,  6.95959596,
        7.06060606,  7.16161616,  7.26262626,  7.36363636,  7.46464646,
        7.56565657,  7.66666667,  7.76767677,  7.86868687,  7.96

In [15]:
np.random.rand(10)#Generates random floating-point numbers between 0 and 1.

array([0.93521124, 0.58438203, 0.5164676 , 0.6245971 , 0.06572661,
       0.8343104 , 0.91006128, 0.75107086, 0.95157483, 0.86034357])

Generates numbers from a normal (Gaussian) distribution.

Characteristics:

Mean ≈ 0
Standard deviation ≈ 1
Can produce:
Negative numbers
Positive numbers
Values greater than 1 or less than -1

Most values fall roughly between -3 and 3.

In [16]:
np.random.randn(10)

array([ 0.06606198,  1.69047364, -1.1831542 , -0.54633161, -1.25892638,
       -0.59804073, -0.92216522,  0.22938323, -0.88103196, -1.04735028])

In [17]:
np.random.randint(10,20,10)#Generates random integers.

array([15, 16, 11, 11, 12, 17, 17, 12, 11, 16])

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print(arr.min())

1


In [24]:
arr.max()

np.int64(9)

In [25]:
print(arr.sum())

45


In [26]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [27]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [28]:
import numpy as np
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [29]:
arr[0,1]

np.int64(2)

In [30]:
print(arr[0,0])

1


In [31]:
print(arr[:,1])

[ 2  7 12 17 22 27]


In [32]:
print(arr[0:2,1:3])

[[2 3]
 [7 8]]


In [33]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [34]:
arr = np.arange(11,21)

In [35]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
bool_idx = arr%2 == 0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [37]:
arr = arr[bool_idx]
arr

array([12, 14, 16, 18, 20])

In [38]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([7,8,9,10,11,12])
a2 - a1

array([6, 6, 6, 6, 6, 6])

In [39]:
a1+a2

array([ 8, 10, 12, 14, 16, 18])

In [40]:
a2 / a1

array([7. , 4. , 3. , 2.5, 2.2, 2. ])

In [41]:
a2//a1

array([7, 4, 3, 2, 2, 2])

In [42]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
arr = arr + 10
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [44]:
a = np.array([1,2,3,4,5])
b = a
b

array([1, 2, 3, 4, 5])

In [45]:
b[2] = 69
b

array([ 1,  2, 69,  4,  5])

In [46]:
a

array([ 1,  2, 69,  4,  5])

In [47]:
b = a.copy()
b

array([ 1,  2, 69,  4,  5])

In [48]:
b[2]=3
b

array([1, 2, 3, 4, 5])

In [49]:
a

array([ 1,  2, 69,  4,  5])

In [50]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])#Matrix Multplication
a @ b

array([[19, 22],
       [43, 50]])

In [51]:
a.T #A Transpose

array([[1, 3],
       [2, 4]])

In [52]:
c = np.arange(4).reshape(2,2)
c

array([[0, 1],
       [2, 3]])

In [53]:
np.hsplit(c,2)  #hsplit = Horizontal Split = Split columns

[array([[0],
        [2]]),
 array([[1],
        [3]])]

In [54]:
np.vsplit(c,2) #vsplit = Vertical Split = Split rows

[array([[0, 1]]), array([[2, 3]])]

In [55]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [56]:
r = np.sum(s,axis = 1)
r


array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [57]:
for i in r:
  if i != 45:
    print("Not Valid")
    break
else:
  print(f"for rows it is valid")


for rows it is valid


In [58]:
c = np.sum(s,axis=0)
for i in r:
  if i != 45:
    print("Not Valid")
    break
else:
  print(f"for columns it is valid")


for columns it is valid


In [59]:
for i in range(0,9,3):
  for j in range(0,9,3):
    v = s[i:i+3,j:j+3]
    print(v.sum())

45
45
45
45
45
45
45
45
45
